- https://github.com/MikeInnes/Flux.jl/blob/master/examples/MNIST.jl

In [1]:
using Flux, MNIST

In [2]:
data = [(trainfeatures(i), onehot(trainlabel(i), 0:9)) for i = 1:60_000]
train = data[1:50_000]
test = data[50_001:60_000]

10000-element Array{Tuple{Array{Float64,1},Array{Int64,1}},1}:
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.

In [3]:
m = Chain(
  Input(784),
  Affine(128), relu,
  Affine( 64), relu,
  Affine( 10), softmax)

Flux.Chain(Any[Flux.Input{1}((784,)), Flux.Affine(Param(784, 128), Param(1, 128)), Flux.relu, Flux.Affine(Param(128, 64), Param(1, 64)), Flux.relu, Flux.Affine(Param(64, 10), Param(1, 10)), Flux.softmax], 10)

In [4]:
model = tf(m)

2017-03-13 22:42:28.665803: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-13 22:42:28.665844: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-03-13 22:42:28.665848: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-13 22:42:28.665853: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.


Flux.TF.Model(Flux.Chain(Any[Flux.Input{1}((784,)), Flux.Affine(Param(784, 128), Param(1, 128)), Flux.relu, Flux.Affine(Param(128, 64), Param(1, 64)), Flux.relu, Flux.Affine(Param(64, 10), Param(1, 10)), Flux.softmax], 10), Session(Ptr{Void} @0x000000014805a6b0), Dict{Flux.Param,TensorFlow.Tensor}(Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 128), <Tensor node_2:1 shape=(1, 128) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 64), <Tensor node_4:1 shape=(1, 64) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(128, 64), <Tensor node_3:1 shape=(128, 64) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(64, 10), <Tensor node_5:1 shape=(64, 10) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(784, 128), <Tensor node:1 shape=(784, 128) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 10), <Tensor node_6:1 shape=(1, 10) dtype=Float32>)), Dict{Any,Any}(Pair{Any,Any}("TensorFlow.nn.relu_2", Any[(Flux.Affine(Param(64, 10), Param(1, 10)), DataFlow.Lin

In [5]:
model(data[1][1])

10-element Array{Float32,1}:
 0.0954587
 0.107971 
 0.101638 
 0.101143 
 0.104277 
 0.0906427
 0.10357  
 0.106997 
 0.0908182
 0.0974839

In [6]:
Flux.train!(model, train, test, η = 1e-4)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] (::Flux.TF.##13#17)(::TensorFlow.Tensor) at ./<missing>:0
 [3] broadcast(::Function, ::TensorFlow.Tensor) at ./broadcast.jl:415
 [4] #12 at /Users/wookyoung/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:52 [inlined]
 [5] #train!#9(::Int64, ::Float64, ::Flux.TF.##12#16, ::TensorFlow.train.GradientDescentOptimizer, ::Function, ::Flux.TF.Model, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}) at /Users/wookyoung/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:56
 [6] (::Flux.#kw##train!)(::Array{Any,1}, ::Flux.#train!, ::Flux.TF.Model, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}) at ./<missing>:0
 [7] include_string(::String, ::String) at ./loading.jl:485
 [8] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/wookyoung/.julia/v0.6/IJulia/src/execute_request.jl:156
 [9] eventloop(::ZMQ.Socket) at /Users

y = Float32[0.0954587 0.107971 0.101638 0.101143 0.104277 0.0906427 0.10357 0.106997 0.0908182 0.0974839]
accuracy(m, test) = 0.1588
y = Float32[0.112878 0.0851877 0.0908585 0.091816 0.10395 0.0802012 0.112048 0.135987 0.0885109 0.0985625]
accuracy(m, test) = 0.3869
y = Float32[0.0878864 0.0334534 0.115824 0.483959 0.0167746 0.0472774 0.032622 0.0491337 0.100671 0.0323983]
accuracy(m, test) = 0.6299
y = Float32[0.0571796 0.000821835 0.0114025 0.0299696 0.131877 0.39911 0.0777704 0.00316711 0.149018 0.139684]
accuracy(m, test) = 0.844
y = Float32[0.0153415 9.35665f-7 4.33114f-5 0.00266004 0.000563149 0.964867 0.00390603 1.49702f-6 0.011593 0.00102394]
accuracy(m, test) = 0.8692
y = Float32[0.00115191 0.00625591 0.0493428 0.25009 0.00154897 0.00498523 0.000166904 0.41842 0.024457 0.243581]
accuracy(m, test) = 0.8755
y = Float32[0.00032824 0.000564357 0.00251635 0.983561 5.21648f-6 0.00675256 1.07315f-5 0.000581958 0.00496591 0.00071412]
accuracy(m, test) = 0.893
y = Float32[2.12749f-6 0.

In [7]:
model(data[1][1])

10-element Array{Float32,1}:
 0.0131847  
 1.57745f-6 
 0.000494634
 0.50863    
 1.52883f-7 
 0.47397    
 1.40895f-5 
 0.000332042
 0.00323067 
 0.000142051

In [13]:
indmax(model(data[1][1])) + 1

5

In [8]:
using UnicodePlots

In [9]:
spy(reshape(data[1][1], (28,28)))

      Sparsity Pattern
      ┌──────────────┐    
    1 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ > 0
      │⠀⠀⠀⢀⣤⣤⣶⣶⣶⣶⣶⡶⠀⠀│ < 0
      │⠀⠀⠀⠈⠻⢿⣿⡋⠛⠀⠀⠀⠀⠀│    
      │⠀⠀⠀⠀⠀⠈⠻⣷⣶⣄⠀⠀⠀⠀│    
      │⠀⠀⠀⠀⠀⠀⣀⣬⣽⣿⠆⠀⠀⠀│    
      │⠀⠀⣀⣤⣶⣿⣿⠿⠛⠁⠀⠀⠀⠀│    
   28 │⠀⠀⠉⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀│    
      └──────────────┘    
      1             28
         nz = 166


In [10]:
spy(reshape(data[2][1], (28,28)))

      Sparsity Pattern
      ┌──────────────┐    
    1 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ > 0
      │⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣤⠀⠀⠀│ < 0
      │⠀⠀⠀⠀⣠⣾⣿⠿⠿⠛⣿⡄⠀⠀│    
      │⠀⠀⠀⣸⣿⠋⠉⠀⠀⠀⣿⡇⠀⠀│    
      │⠀⠀⠀⣿⡏⠀⠀⢀⣴⡿⠛⠁⠀⠀│    
      │⠀⠀⠀⢿⣿⣿⣿⠟⠋⠁⠀⠀⠀⠀│    
   28 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
      └──────────────┘    
      1             28
         nz = 176
