- https://github.com/MikeInnes/Flux.jl/blob/master/examples/MNIST.jl
- https://mikeinnes.github.io/Flux.jl/latest/examples/logreg.html

In [1]:
using Flux, MNIST

In [2]:
data = [(trainfeatures(i), onehot(trainlabel(i), 0:9)) for i = 1:60_000]
train = data[1:50_000]
test = data[50_001:60_000]

10000-element Array{Tuple{Array{Float64,1},Array{Int64,1}},1}:
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.

In [3]:
m = Chain(
  Input(784),
  Affine(128), relu,
  Affine( 64), relu,
  Affine( 10), softmax)

Flux.Chain(Any[Flux.Input{1}((784,)), Flux.Affine(Param(784, 128), Param(1, 128)), Flux.relu, Flux.Affine(Param(128, 64), Param(1, 64)), Flux.relu, Flux.Affine(Param(64, 10), Param(1, 10)), Flux.softmax], 10)

In [4]:
model = tf(m)

2017-03-14 22:30:05.919437: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-14 22:30:05.919485: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-03-14 22:30:05.919489: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-03-14 22:30:05.919494: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.


Flux.TF.Model(Flux.Chain(Any[Flux.Input{1}((784,)), Flux.Affine(Param(784, 128), Param(1, 128)), Flux.relu, Flux.Affine(Param(128, 64), Param(1, 64)), Flux.relu, Flux.Affine(Param(64, 10), Param(1, 10)), Flux.softmax], 10), Session(Ptr{Void} @0x0000000143ab4f70), Dict{Flux.Param,TensorFlow.Tensor}(Pair{Flux.Param,TensorFlow.Tensor}(Param(64, 10), <Tensor node_5:1 shape=(64, 10) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(784, 128), <Tensor node:1 shape=(784, 128) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(128, 64), <Tensor node_3:1 shape=(128, 64) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 128), <Tensor node_2:1 shape=(1, 128) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 64), <Tensor node_4:1 shape=(1, 64) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 10), <Tensor node_6:1 shape=(1, 10) dtype=Float32>)), Dict{Any,Any}(Pair{Any,Any}("TensorFlow.nn.relu_2", Any[(Flux.Affine(Param(64, 10), Param(1, 10)), DataFlow.Lin

In [5]:
model(data[1][1])

10-element Array{Float32,1}:
 0.101359 
 0.117402 
 0.0912359
 0.0929812
 0.107271 
 0.0889401
 0.091921 
 0.0926007
 0.109281 
 0.107009 

In [6]:
Flux.train!(model, train, test, η = 1e-4)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] (::Flux.TF.##13#17)(::TensorFlow.Tensor) at ./<missing>:0
 [3] broadcast(::Function, ::TensorFlow.Tensor) at ./broadcast.jl:415
 [4] #12 at /Users/wookyoung/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:52 [inlined]
 [5] #train!#9(::Int64, ::Float64, ::Flux.TF.##12#16, ::TensorFlow.train.GradientDescentOptimizer, ::Function, ::Flux.TF.Model, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}) at /Users/wookyoung/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:56
 [6] (::Flux.#kw##train!)(::Array{Any,1}, ::Flux.#train!, ::Flux.TF.Model, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}) at ./<missing>:0
 [7] include_string(::String, ::String) at ./loading.jl:485
 [8] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/wookyoung/.julia/v0.6/IJulia/src/execute_request.jl:156
 [9] eventloop(::ZMQ.Socket) at /Users

y = Float32[0.101359 0.117402 0.0912359 0.0929812 0.107271 0.0889401 0.091921 0.0926007 0.109281 0.107009]
accuracy(m, test) = 0.0986
y = Float32[0.0961203 0.0821184 0.0890894 0.121279 0.088391 0.092387 0.081735 0.125229 0.0996388 0.124012]
accuracy(m, test) = 0.5286
y = Float32[0.0602504 0.0158355 0.0267886 0.729032 0.0150675 0.0162104 0.00392011 0.053222 0.0585485 0.0211245]
accuracy(m, test) = 0.6692
y = Float32[0.103362 0.000639083 0.0297175 0.0163969 0.187571 0.397717 0.0505212 0.0135012 0.100797 0.0997772]
accuracy(m, test) = 0.8399
y = Float32[0.0217005 1.58826f-6 4.30124f-5 0.00211281 0.000486789 0.967454 0.00158593 7.1386f-6 0.0061139 0.000494708]
accuracy(m, test) = 0.8684
y = Float32[0.000849722 0.00248931 0.0385612 0.359859 0.00182428 0.0121296 0.000147139 0.162289 0.0477493 0.374101]
accuracy(m, test) = 0.8741
y = Float32[0.000245754 0.000229379 0.00121345 0.991782 1.19986f-5 0.00353585 2.54625f-6 0.000881996 0.0016811 0.000416232]
accuracy(m, test) = 0.8975
y = Float32[2.

In [8]:
model(data[1][1])

10-element Array{Float32,1}:
 0.0166987  
 4.01045f-6 
 0.000373073
 0.0993163  
 2.30343f-7 
 0.879802   
 2.65279f-5 
 0.00071927 
 0.00300555 
 5.46454f-5 

In [9]:
indmax(model(data[1][1])) - 1

5

In [10]:
indmax(model(data[2][1])) - 1

0

In [11]:
using UnicodePlots

In [12]:
spy(reshape(data[1][1], (28,28)))

      Sparsity Pattern
      ┌──────────────┐    
    1 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ > 0
      │⠀⠀⠀⢀⣤⣤⣶⣶⣶⣶⣶⡶⠀⠀│ < 0
      │⠀⠀⠀⠈⠻⢿⣿⡋⠛⠀⠀⠀⠀⠀│    
      │⠀⠀⠀⠀⠀⠈⠻⣷⣶⣄⠀⠀⠀⠀│    
      │⠀⠀⠀⠀⠀⠀⣀⣬⣽⣿⠆⠀⠀⠀│    
      │⠀⠀⣀⣤⣶⣿⣿⠿⠛⠁⠀⠀⠀⠀│    
   28 │⠀⠀⠉⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀│    
      └──────────────┘    
      1             28
         nz = 166


In [13]:
spy(reshape(data[2][1], (28,28)))

      Sparsity Pattern
      ┌──────────────┐    
    1 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ > 0
      │⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣤⠀⠀⠀│ < 0
      │⠀⠀⠀⠀⣠⣾⣿⠿⠿⠛⣿⡄⠀⠀│    
      │⠀⠀⠀⣸⣿⠋⠉⠀⠀⠀⣿⡇⠀⠀│    
      │⠀⠀⠀⣿⡏⠀⠀⢀⣴⡿⠛⠁⠀⠀│    
      │⠀⠀⠀⢿⣿⣿⣿⠟⠋⠁⠀⠀⠀⠀│    
   28 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
      └──────────────┘    
      1             28
         nz = 176


In [14]:
data[1][2]

10-element Array{Int64,1}:
 0
 0
 0
 0
 0
 1
 0
 0
 0
 0

In [15]:
onecold(data[1][2], 0:9)

5

In [16]:
 onecold(model(data[1][1]), 0:9)

5