- https://github.com/MikeInnes/Flux.jl/blob/master/examples/MNIST.jl

In [22]:
using Flux, MNIST

In [25]:
data = [(trainfeatures(i), onehot(trainlabel(i), 0:9)) for i = 1:60_000]
train = data[1:50_000]
test = data[50_001:60_000]

10000-element Array{Tuple{Array{Float64,1},Array{Int64,1}},1}:
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
 ([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.

In [26]:
m = Chain(
  Input(784),
  Affine(128), relu,
  Affine( 64), relu,
  Affine( 10), softmax)

Flux.Chain(Any[Flux.Input{1}((784,)), Flux.Affine(Param(784, 128), Param(1, 128)), Flux.relu, Flux.Affine(Param(128, 64), Param(1, 64)), Flux.relu, Flux.Affine(Param(64, 10), Param(1, 10)), Flux.softmax], 10)

In [27]:
model = tf(m)

Flux.TF.Model(Flux.Chain(Any[Flux.Input{1}((784,)), Flux.Affine(Param(784, 128), Param(1, 128)), Flux.relu, Flux.Affine(Param(128, 64), Param(1, 64)), Flux.relu, Flux.Affine(Param(64, 10), Param(1, 10)), Flux.softmax], 10), Session(Ptr{Void} @0x000000013fac85d0), Dict{Flux.Param,TensorFlow.Tensor}(Pair{Flux.Param,TensorFlow.Tensor}(Param(64, 10), <Tensor node_5:1 shape=(64, 10) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 128), <Tensor node_2:1 shape=(1, 128) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 10), <Tensor node_6:1 shape=(1, 10) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(128, 64), <Tensor node_3:1 shape=(128, 64) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(784, 128), <Tensor node:1 shape=(784, 128) dtype=Float32>),Pair{Flux.Param,TensorFlow.Tensor}(Param(1, 64), <Tensor node_4:1 shape=(1, 64) dtype=Float32>)), Dict{Any,Any}(Pair{Any,Any}("TensorFlow.nn.relu_2", Any[(Flux.Affine(Param(64, 10), Param(1, 10)), DataFlow.Lin

In [28]:
model(data[1][1])

10-element Array{Float32,1}:
 0.0996712
 0.0911464
 0.110021 
 0.100629 
 0.112456 
 0.0859974
 0.0901273
 0.112069 
 0.096973 
 0.100909 

In [29]:
Flux.train!(model, train, test, η = 1e-4)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] (::Flux.TF.##13#17)(::TensorFlow.Tensor) at ./<missing>:0
 [3] broadcast(::Function, ::TensorFlow.Tensor) at ./broadcast.jl:415
 [4] #12 at /Users/wookyoung/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:52 [inlined]
 [5] #train!#9(::Int64, ::Float64, ::Flux.TF.##12#16, ::TensorFlow.train.GradientDescentOptimizer, ::Function, ::Flux.TF.Model, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}) at /Users/wookyoung/.julia/v0.6/Flux/src/backend/tensorflow/model.jl:56
 [6] (::Flux.#kw##train!)(::Array{Any,1}, ::Flux.#train!, ::Flux.TF.Model, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}, ::Array{Tuple{Array{Float64,1},Array{Int64,1}},1}) at ./<missing>:0
 [7] include_string(::String, ::String) at ./loading.jl:485
 [8] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/wookyoung/.julia/v0.6/IJulia/src/execute_request.jl:156
 [9] eventloop(::ZMQ.Socket) at /Users

y = Float32[0.0996712 0.0911464 0.110021 0.100629 0.112456 0.0859974 0.0901273 0.112069 0.096973 0.100909]
accuracy(m, test) = 0.0514
y = Float32[0.10994 0.0760491 0.106025 0.096689 0.117616 0.0817774 0.0891879 0.110395 0.105719 0.106602]
accuracy(m, test) = 0.391
y = Float32[0.0535591 0.0386932 0.0420305 0.683349 0.0149013 0.0277118 0.0199532 0.0294821 0.0645013 0.0258188]
accuracy(m, test) = 0.6789
y = Float32[0.0224534 0.00194407 0.0249641 0.030619 0.141841 0.402227 0.0426406 0.0132824 0.13719 0.182839]
accuracy(m, test) = 0.837
y = Float32[0.011003 2.04282f-6 0.000224882 0.00474453 0.000407029 0.962111 0.00281314 6.5262f-6 0.0173116 0.00137615]
accuracy(m, test) = 0.8741
y = Float32[0.00132644 0.00490953 0.057068 0.340217 0.00173608 0.00823914 0.00033902 0.273011 0.02455 0.288604]
accuracy(m, test) = 0.8818
y = Float32[0.000153575 0.000629035 0.000568233 0.992832 8.2904f-6 0.002163 1.15699f-6 0.00105456 0.00194022 0.00064996]
accuracy(m, test) = 0.8964
y = Float32[1.22225f-5 0.9836

In [30]:
model(data[1][1])

10-element Array{Float32,1}:
 0.0139753  
 6.80918f-7 
 0.000245888
 0.144006   
 2.90812f-7 
 0.83998    
 3.38247f-5 
 0.000245232
 0.00142875 
 8.39817f-5 

In [31]:
indmax(model(data[1][1])) - 1

5

In [32]:
indmax(model(data[2][1])) - 1

0

In [33]:
using UnicodePlots

In [34]:
spy(reshape(data[1][1], (28,28)))

      Sparsity Pattern
      ┌──────────────┐    
    1 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ > 0
      │⠀⠀⠀⢀⣤⣤⣶⣶⣶⣶⣶⡶⠀⠀│ < 0
      │⠀⠀⠀⠈⠻⢿⣿⡋⠛⠀⠀⠀⠀⠀│    
      │⠀⠀⠀⠀⠀⠈⠻⣷⣶⣄⠀⠀⠀⠀│    
      │⠀⠀⠀⠀⠀⠀⣀⣬⣽⣿⠆⠀⠀⠀│    
      │⠀⠀⣀⣤⣶⣿⣿⠿⠛⠁⠀⠀⠀⠀│    
   28 │⠀⠀⠉⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀│    
      └──────────────┘    
      1             28
         nz = 166


In [35]:
spy(reshape(data[2][1], (28,28)))

      Sparsity Pattern
      ┌──────────────┐    
    1 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│ > 0
      │⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣤⠀⠀⠀│ < 0
      │⠀⠀⠀⠀⣠⣾⣿⠿⠿⠛⣿⡄⠀⠀│    
      │⠀⠀⠀⣸⣿⠋⠉⠀⠀⠀⣿⡇⠀⠀│    
      │⠀⠀⠀⣿⡏⠀⠀⢀⣴⡿⠛⠁⠀⠀│    
      │⠀⠀⠀⢿⣿⣿⣿⠟⠋⠁⠀⠀⠀⠀│    
   28 │⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀│    
      └──────────────┘    
      1             28
         nz = 176
